# -*- coding: utf-8 -*-
"""Filter_and_summarise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lOXzccNaq8dM_SNA2l1pSb6STEKtn7rV
"""

# !pip install python-telegram-bot==13.7
import pandas as pd
import openai
import telegram

def ask_gpt(prompt):
    completions = openai.Completion.create(
        engine=model_engine,
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.7,
    )

    message = completions.choices[0].text.strip()
    return message
openai.api_key = "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"
model_engine = "text-davinci-003"  # or any other GPT-3.5 engine, such as "text-curie-001" or "text-babbage-001"

db=pd.read_json("app updates repository .json")
data = pd.read_csv("apps.csv")

updates = {}
for i in range(len(list(data["name"]))):
  updates[data["name"][i]] = {}
log = ""

for i in range(len(data["name"])):
  try:
    if db[data["name"][i]][len(db["datetime"])-1] != db[data["name"][i]][len(db["datetime"])-2]:
        # check apple and save
      if db[data["name"][i]][len(db["datetime"])-1]["apple"] != db[data["name"][i]][len(db["datetime"])-2]["apple"]:
        updates[data["name"][i]]["app store"]=db[data["name"][i]][len(db["datetime"])-1]["apple"]
        log = log + "new update found in " + data["name"][i] + " apple"\n

      # check google and save
      if db[data["name"][i]][len(db["datetime"])-1]["google"] != db[data["name"][i]][len(db["datetime"])-2]['google']:
        updates[data["name"][i]]["play store"]=db[data["name"][i]][len(db["datetime"])-1]["google"]
        log = log + "new update found in " + data["name"][i] + " google\n"
  except Exception as e:
     print(e)

def summarise(name):
  prompt = '''I have updates of the app'''+ name +'''from google play store and apple app store. Here are they ''' + str(updates[name])+ '''. If they are same then summarise them in bullet points like a news reporter. If they are different then pick the most relevant one out of the two and summarise them in bullet points like a reporter.  Answer only bullet points no extra text please, not even a sentence above or below. The bullet points should include only relevant points and should combine the apps store and play store updates. Make it sound like they are updates from company rather than apps. Don't include bug fixes and experience enhancements in bullet points.'''
  response = ask_gpt(prompt)
  return response

final_string = "Good morning!"
for i in range(len(list(updates.keys()))):
  final_string = final_string + "\nUpdates from " + list(updates.keys())[i] + ": \n"
  final_string = final_string + summarise(list(updates.keys())[i]) + "\n"

# Replace YOUR_TOKEN with the token provided by BotFather
bot = telegram.Bot(token='5878600641:AAGRQdzIfzh7OJYk8Wiik7KR7IjCCHSUZ7w')

# Replace CHAT_ID with the chat ID of the recipient
bot.send_message(chat_id='929442149', text=log)
bot.send_message(chat_id='929442149', text=final_string)



# def ask_gpt(prompt):
#     completions = openai.ChatCompletion.create(
#         model=model_engine,
#         messages=[{"role": "system", "content" : "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: 2021-09-01\nCurrent date: 2023-03-02"},
# {"role": "user", "content" : "How are you?"},
# {"role": "assistant", "content" : "I am doing well"}, {"role": "user", "content" : prompt}],
#         max_tokens=1024,