# -*- coding: utf-8 -*-
"""Product_updates_scrape_and_dump.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GWmg16O4XK9whH6rUqWFpdIvmVqY3_7T
"""

!pip install cloudscraper
!pip install python-telegram-bot==13.7
import cloudscraper
scraper = cloudscraper.create_scraper() 
from datetime import datetime
from bs4 import BeautifulSoup 
import pandas as pd
from datetime import datetime
import telegram

def get_apple_update(url):
  scraper = cloudscraper.create_scraper()
  a= scraper.get(url).text
  soup = BeautifulSoup(a, "html.parser") 
  return soup.find(class_ = "we-truncate we-truncate--multi-line we-truncate--interactive").get_text().replace("\n","")
def get_google_update(url):
  scraper = cloudscraper.create_scraper()
  a= scraper.get(url).text
  soup = BeautifulSoup(a, "html.parser") 
  return soup.find_all(class_ = "SfzRHd")[3].get_text()

data = pd.read_csv('apps.csv')
db = pd.read_csv('app updates repository .csv')
print(db)
log = ""

# today
dt = datetime.now()
db.loc[len(db)] = [dt,list([]),list([]),list([])]
log = log + "Started at " + str(dt) + "\n"
ind = db.index[db['datetime'] == dt].tolist()[len(db.index[db['datetime'] == dt].tolist())-1]

for i in range(len(data["name"])):
  try:
    apple = get_apple_update(data["apple"][i])
    log = log + data["name"][i] + " apple Fetched\n"
  except Exception as e:
    apple = ""
    log = log + "\n\n\n" + data["name"][i] + " apple error" + str(e) +"\n\n\n"
  try:
    google = get_google_update(data["google"][i])
    log = log + data["name"][i] + " google Fetched\n"
  except Exception as e:
    google = ""
    log = log + "\n\n\n" + data["name"][i] + " google error" + str(e) +"\n\n\n"
  db[data["name"][i]][ind].extend([apple,google])

db.to_csv('app updates repository .csv', index=False)

# Replace YOUR_TOKEN with the token provided by BotFather
bot = telegram.Bot(token='5878600641:AAGRQdzIfzh7OJYk8Wiik7KR7IjCCHSUZ7w')

# Replace CHAT_ID with the chat ID of the recipient
bot.send_message(chat_id='929442149', text=log)